@startuml
class ApplicationController{
ApplicationController()
initialize()
setStage()
LoadDatafromFileToCollections()
createItem()
resetFields()
loadDataItem()
addItem()
deleteItem()
clearAllItems()
saveData()
closeApplication()
}
ApplicationController <--> ToDoListApplication
@enduml